### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dolodi** [slack69/csgo-dma-overlay#4]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'boost/predef/architecture/x86/32.h': No such file or directory	csgo-dma-overlay	C:\Users\jayyy\Desktop\csgo-dma-overlay-master\csgo-dma-overlay-master\dma\boost_1_69_0\boost\predef\architecture\x86.h	8

**Comment by slack2450** [comment]
Sounds like boost isn't installed correctly
